debug: false
url: http://udb-uitpas.dev
labels:
  PASPARTOE: 'Paspartoe'
  UITPAS: 'UiTPAS'
  UITPAS_GENT: 'UiTPAS Gent'
  UITPAS_OOSTENDE: 'UiTPAS Oostende'
  UITPAS_REGIO_AALST: 'UiTPAS regio Aalst'
  UITPAS_DENDER: 'UiTPAS Dender'
  UITPAS_ZUIDWEST: 'UiTPAS Zuidwest'
  UITPAS_MECHELEN: 'UiTPAS Mechelen'
  UITPAS_KEMPEN: 'UiTPAS Kempen'
  UITPAS_MAASMECHELEN: 'UiTPAS Maasmechelen'
uitid:
  consumer:
    key: ***
    secret: ***
  base_url: https://acc.uitid.be/uitid/rest/
jwt:
  uitid:
    keys:
      public:
        file: public.pem
    validation:
      iss: http://culudb-jwt-provider.dev
  auth0:
    keys:
      public:
        file: public-auth0.pem
    validation:
      iss: https://publiq-acc.eu.auth0.com/
 validation:
   iss: http://culudb-jwt-provider.dev
cors:
  origins:
    - http://udb-app.dev
    - http://localhost:9999
sentry:
  dsn: *
  environment: testing
