debug: false
bootstrap: []
log.command_bus:
  - type: file
    path: ../log/command_bus.log
    level: DEBUG
  - type: socketioemitter
    level: INFO
uitid:
  consumer:
    key: ***
    secret: ***
  base_url: https://acc.uitid.be/uitid/rest/
udb3_organizer_base_url: http://udb-silex.dev/organizers/ # Trailing slash required!
udb3_permission_base_url: http://udb-silex.dev/event/%s/permission
jwt:
  keys:
    public:
      file: public.pem
  validation:
    iss: http://culudb-jwt-provider.dev
